# Generated by Django 4.1.2 on 2022-10-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("birthDate", models.DateField(blank=True, null=True)),
                ("contractStartDate", models.DateField(blank=True, null=True)),
                ("contractEndDate", models.DateField(blank=True, null=True)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
    ]
