# Generated by Django 4.1.2 on 2022-10-24 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contract", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
